In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [4]:
df.head

<bound method NDFrame.head of       Customer ID  Age  Gender Item Purchased     Category  \
0               1   55    Male         Blouse     Clothing
1               2   19    Male        Sweater     Clothing
2               3   50    Male          Jeans     Clothing
3               4   21    Male        Sandals     Footwear
4               5   45    Male         Blouse     Clothing
...           ...  ...     ...            ...          ...
3895         3896   40  Female         Hoodie     Clothing
3896         3897   52  Female       Backpack  Accessories
3897         3898   46  Female           Belt  Accessories
3898         3899   44  Female          Shoes     Footwear
3899         3900   52  Female        Handbag  Accessories

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter
1                        64          Maine    L     Maroon  Winter
2                        73  Massachusetts    S     Maroon  Spring
3                        90   Rhode Island    M     Maroon  Spring
4                        49         Oregon    M  Turquoise  Spring
...                     ...            ...  ...        ...     ...
3895                     28       Virginia    L  Turquoise  Summer
3896                     49           Iowa    L      White  Spring
3897                     33     New Jersey    L      Green  Spring
3898                     77      Minnesota    S      Brown  Summer
3899                     81     California    M      Beige  Spring

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.1                 Yes         Express              Yes
1               3.1                 Yes         Express              Yes
2               3.1                 Yes   Free Shipping              Yes
3               3.5                 Yes    Next Day Air              Yes
4               2.7                 Yes   Free Shipping              Yes
...             ...                 ...             ...              ...
3895            4.2                  No  2-Day Shipping               No
3896            4.5                  No    Store Pickup               No
3897            2.9                  No        Standard               No
3898            3.8                  No         Express               No
3899            3.1                  No    Store Pickup               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0                Yes                  14          Venmo            Fortnightly
1                Yes                   2           Cash            Fortnightly
2                Yes                  23    Credit Card                 Weekly
3                Yes                  49         PayPal                 Weekly
4                Yes                  31         PayPal               Annually
...              ...                 ...            ...                    ...
3895              No                  32          Venmo                 Weekly
3896              No                  41  Bank Transfer              Bi-Weekly
3897              No                  24          Venmo              Quarterly
3898              No                  24          Venmo                 Weekly
3899              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]>

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [9]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [10]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [19]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [21]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [25]:
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [26]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [ ]:
# create a column age_group 
labels = ['young_adult', 'adult', 'middle_aged', 'senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [35]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  middle_aged
1   19  young_adult
2   50  middle_aged
3   21  young_adult
4   45  middle_aged
5   46  middle_aged
6   63       senior
7   27  young_adult
8   26  young_adult
9   57  middle_aged

In [36]:
# create column purcahse_frequency_days 
frequency_mapping = { 
    'fortynighty': 14,
    'weekly': 7,
    'monthly': 30,
    'quarterly': 90,
    'bi-weekly': 14,
    'annually': 365,
    'every 3 months': 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [37]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [39]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [40]:
df = df.drop('promo_code_used', axis=1)

In [41]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [43]:
%pip install "psycopg[binary]" sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting psycopg[binary]
  Downloading psycopg-3.3.3-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: tzdata in c:\users\sai kiran\appdata\local\programs\python\python313\lib\site-packages (from psycopg[binary]) (2025.3)
Collecting psycopg-binary==3.3.3 (from psycopg[binary])
  Downloading psycopg_binary-3.3.3-cp313-cp313-win_amd64.whl.metadata (2.7 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading psycopg-3.3.3-py3-none-any.whl (212 kB)
Downloading psycopg_binary-3.3.3-cp313-cp313-win_amd64.whl (3.6 MB)
   ---------------------------------------- 0.0/3.6 MB ? eta -:--:--
   -------------------------------------- - 3.4/3.6 MB 18.4 MB/s eta 0:00:01
   ---------------------------------------- 3.6/3.6 MB 14.7 MB/s  0:00:00
Downloading sqlalchemy-2.0.49-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 16.5 MB/s  0:00:00
Downloading greenlet-3.5.0-cp313-cp313-win_amd64.whl (238 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, psycopg-binary, psycopg, greenlet, sqlalchemy

   -------- ------------------------------- 1/5 [psycopg-binary]
   ---------------- ----------------------- 2/5 [psycopg]
   ---------------- ----------------------- 2/5 [psycopg]
   ---------------- ----------------------- 2/5 [psycopg]
   ---------------- ----------------------- 2/5 [psycopg]
   ---------------- ----------------------- 2/5 [psycopg]
   ---------------- ----------------------- 2/5 [psycopg]
   ---------------- ----------------------- 2/5 [psycopg]
   ------------------------ --------------- 3/5 [greenlet]
   ------------------------ --------------- 3/5 [greenlet]
   ------------------------ --------------- 3/5 [greenlet]
   ------------------------ --------------- 3/5 [greenlet]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   -------------------------------- ------- 4/5 [sqlalchemy]
   ---------------------------------------- 5/5 [sqlalchemy]

Successfully installed greenlet-3.5.0 psycopg-3.3.3 psycopg-binary-3.3.3 sqlalchemy-2.0.49 typing-extensions-4.15.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [49]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"                # default user
password = "8977540870"           # your specific password
host = "localhost"                   # if running locally
port = "5432"                        # default PostgreSQL port
database = "customer_behavior"                # the default database name

engine = create_engine(f"postgresql+psycopg://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"              # Choosing the table name as 'customer'
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.